# Generated by Django 3.2.4 on 2021-06-06 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dinosaurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dinosaur',
            options={'verbose_name': 'Dinosaur', 'verbose_name_plural': 'Dinosaurs'},
        ),
    ]
