"""empty message

Revision ID: 606177f1641a
Revises: 
Create Date: 2021-06-19 22:39:44.639694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '606177f1641a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dinosaur', sa.Column('likes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dinosaur', 'likes')
    # ### end Alembic commands ###
