version: '3.7'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000 # localPort:dockerPort mapping
    volumes:
    - .:/app  # localPath: dockerPath mapping
    depends_on:
      - db

  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: ms_admin
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql # localDbData:dockerDbData path mapping
    ports:
      - 33006:3306 # local db:docker db port mapping
